### ISSUE TITLE
Unable to load application

### ISSUE THREAD

**Issue by srivaranasi** [nachu27/logicAstroKPCharts#2]
![image](https://user-images.githubusercontent.com/58924136/205991658-d51820f9-9056-4276-86fc-955678bb7c06.png)

hi there,

I am unable to load the application due to missing folder swiss-eph, can you please direct me which NuGet package I should load to get that folder to make the application work or kindly update the repo.

Thank you

**Comment by nachu27** [comment]
Hi,
Let me make some changes and upload a package for it in few days.
Thanks
    On Tuesday, December 6, 2022 at 11:58:47 PM GMT+5:30, srivaranasi ***@***.***> wrote:  
 
 




hi there,

I am unable to load the application due to missing folder swiss-eph, can you please direct me which NuGet package I should load to get that folder to make the application work or kindly update the repo.

Thank you

**Comment by nachu27** [comment]
The source code is updated.

As well the swiss ephemeris files are stored in proper folders and a sample "release folder" is also uploaded for reference.

**Comment by srivaranasi** [comment]
Thank you for your support. I was more keen to understand how we prepare charts manually, so googled it and found your repo. I would really appreciate if you could help me to understand the basics please ping me if you can Thank you. [sri varanasi](https://www.linkedin.com/in/srivaranasi/)

**Comment by nachu27** [comment]
Send me your email id / phone number and I will ping you.
    On Tuesday, December 13, 2022 at 02:53:16 AM GMT+5:30, srivaranasi ***@***.***> wrote:  
 
 


Thank you for your support. I was more keen to understand how we prepare charts manually, so googled it and found your repo. I would really appreciate if you could help me to understand the basics please ping me if you can Thank you. sri varanasi

**Comment by srivaranasi** [comment]
Thanks, I can't share it here, so please send link request to my LinkedIn account ---> [Sri Varanasi] (https://www.linkedin.com/in/srivaranasi/) will get touch with you. Thanks.

**Comment by nachu27** [comment]
This is my email address.
***@***.***

ThanksNachi.
    On Wednesday, December 14, 2022 at 12:43:58 PM GMT+5:30, srivaranasi ***@***.***> wrote:  
 
 


Thanks, I can't share it here, so please send link request to my LinkedIn account ---> [Sri Varanasi] (https://www.linkedin.com/in/srivaranasi/) will get touch with you. Thanks.

**Comment by srivaranasi** [comment]
Github will hide the emails and I can't see your email neither I can't share here

**Comment by nachu27** [comment]
LinkedIn does not allow me to message you as well without paying them for premium service.

Go to the web site logicastro and you can find the it in the about us section.
logicastro.com
-nachu27--at--yahoo--com-
    On Wednesday, December 14, 2022 at 02:53:48 PM GMT+5:30, srivaranasi ***@***.***> wrote:  
 
 


Github will hide the emails and I can't see your email neither I can't share here
